use_frameworks!

platform :ios, '8.0'

target 'SYZPermissionKit_Example' do
  pod 'SYZPermissionKit', :path => '../'

  target 'SYZPermissionKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
